package main.java.com.dougronthebold.DAPlayletTwo.graph_melody;
/*
 * Currently, an object to store phrases generated by the Graph melody design efforts.
 * Currently there is no implication of multiple parts, so phrases are stored in hashmaps
 * with the key being the start point
 */
public class Phrase {

	public double phraseStartPoint;
	public double firstNotePos;
	public double lastNotePos;
	
	public Phrase(double psp, double fnp, double lnp){
		this.phraseStartPoint = psp;
		this.firstNotePos = fnp;
		this.lastNotePos = lnp;
	}
	
	public String toString(){
		String ret = "Phrase:";
		ret += " phraseStartPoint - " + phraseStartPoint;
		ret += " firstNotePos - " + firstNotePos;
		ret += " lastNotePos - " + lastNotePos;
		return ret;
	}
}
